language: node_js
node_js:
- 14
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key:
    secure: 7IMhH9reNUL0icSqsE8U0cDPhlKtqEqi0DqoJIWu4AB/ssGwLoboDsZH3eVzv0Tcrmre36gVkmmB1sBRP2V7cB8MW/9zsqGY2Hc/o9PWIcN4wL/1sZBhspiRk15Mnfb5c2lWBlNiEewg8hjRVLuTp8i53ZDU09QnaA02bRWs+sZsUIItFX/WoStrpWSvpczKH5G9abQ7Qp0Em37lz8SUL4gK2gKM7roqmd+6lkMcIpKdG4eaSdFM9fLfdPXbSfbqkO5K0084/GVVIK0hCjFDkzCh+yI2iX8GR/vl/juaZgs+Gr2wGONbqgnWzY+zZyq21Sq/JZoDkoazmYy0B2E1JeBVpD/u9whpmsjQ9voPH5sbi8+Mr3ltpXvwJgPVUDSg+Nv27Is4TgabMXAcu7TTxSmd+nVCwVGK2GXOBThSE7xnZS3C69SsaYw8W8/BdzSUTn+3hkqGNQqrhw0kNoo3ijvB/rGwDPpzz4eUNArOw3gHSkuTRGxhg9nblR9RzduEe/qWi/+c+khApFr2ZSbsA6FvRm85sv/YsgVFoOvuKyqNHQSOu2s1aLZEegMubEfMghExBm9kqyT7Kh4OXh+mS79D6Lr/nsDXcjmzeAOqjzHssK6WuYm2gkVbpIltKWrj2iPEptem/6XqM7Kgs3F2PyvMB4xeZQ5ZXGayFxPbdwI=
