language: node_js
node_js:
- 14
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key:
    secure: xCKxFI7ctQYgdgdufosPLWvxyO09ZHZFRoFfP4nimOtm7T79DoBcE7AWtW/Gr3FN+fKqEDK960LFkIsakMBLKnUleaNYZaDBol075qL2xBN1xvUJ5TqTXwB48GdVq1f33Lc45ReDRQt7afwYnCu4BT3qowvl5iOVJiDWIVb7hwT3MQla960782JZfnVnyJ4UfwateeI/6J+BhLPK33oTl95Wq97Qrzba/TNYg2hbh4arRxdhTra86pCRtfTNm5JbBWoIC9RwS03B4VMbGxElWcrSrci4rBZd8mLBnvEbfNBKlfl0jg7xWpm/t/G4mm1DHxipb4Hzb0KDDELbqZD8gUsTZb4i2pO2iXA7dggZJS5/L4hHRPiJ8BxMLwhuHPgEyO00g1dghdQE7AO64+izQAa7BVZX332l6m3qyCM0BZAPxpuNxk/9b3Eg9qhLmq8s41R0JmNlMcpxatROoVq0MqUOocxb7zv47YAEgNFMSmOj2SQuH9p5j9eokgcamVM5XDsnD1rBquC5ll6uQYmdtg+ilTXKvQzZ6doRh4vRHDCHFQsCORak9a3IO25ZJE5OZt3TpkCOzHSa9trJ8D6CrhUCb65Xe7g7k2RI7IGV9vaKsZTZacRioB9zBww2bHzvXuIEEZpACc25cCWnFgASMd+/ezJa99ILIT6MM9qYh4U=
  app: loggerjs